workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "3.29.2"  # Explicit version
      groups:
        - ios
    scripts:
      - name: Precache Flutter iOS Artifacts
        script: |
          flutter precache --ios --android
          ls $FLUTTER_ROOT/bin/cache/artifacts/engine/ios/  # Verify files

      - name: Install Pods (Fixed)
        script: |
          cd ios
          # Use absolute path to Flutter engine
          flutter_engine_path="$FLUTTER_ROOT/bin/cache/artifacts/engine/ios"
          echo "pod 'Flutter', :path => '$flutter_engine_path'" >> Podfile
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign