workflows:
  ios-sideloadly-workflow:
    name: iOS Build for Sideloadly
    environment:
      flutter: "3.29.2"
      xcode: latest
      cocoapods: default
    instance_type: mac_mini_m1
    scripts:
      - name: Setup Flutter
        script: |
          flutter precache --ios
          flutter pub get

      - name: Fix Flutter Engine Path
        script: |
          # Ensure Flutter engine is properly linked
          flutter pub cache repair
          cd ios
          flutter pub get
          cd ..

      - name: Install Pods
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios
          pod cache clean --all
          pod repo update
          pod install --verbose
          cd ..

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          cd ios
          mkdir -p build/ipa
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -archivePath build/Runner.xcarchive
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ios/build/ipa/*.ipa