workflows:
  ios-sideloadly-workflow:
    environment:
      flutter: "3.29.2"
      xcode: latest
      cocoapods: default
    instance_type: mac_mini_m1
    scripts:
      - name: Force Flutter Engine Download
        script: |
          # Completely refresh Flutter cache
          rm -rf ${FLUTTER_ROOT}/bin/cache/artifacts/engine/ios
          flutter precache --ios --force
          flutter pub get

      - name: Verify Flutter Engine
        script: |
          echo "Checking Flutter engine at:"
          ls -la ${FLUTTER_ROOT}/bin/cache/artifacts/engine/ios
          if [ ! -f "${FLUTTER_ROOT}/bin/cache/artifacts/engine/ios/Flutter.podspec" ]; then
            echo "ERROR: Flutter.podspec missing!"
            flutter doctor -v
            exit 1
          fi

      - name: Install Pods with Correct Paths
        script: |
          cd ios
          # Ensure Podfile uses absolute path
          FLUTTER_ABS_PATH=$(which flutter | xargs dirname | xargs dirname)
          sed -i '' "s|flutter_application_path = '../'|flutter_application_path = '${FLUTTER_ABS_PATH}'|" Podfile
          
          # Clean and install pods
          pod cache clean --all
          pod repo update
          pod install --verbose
          cd ..

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -archivePath build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/ipa/*.ipa