workflows:
  ios-workflow:
    name: iOS Build
    environment:
      groups:
        - ios  # Contains iOS code signing credentials
      vars:
        FLUTTER_VERSION: "3.29.2"  # Matches your local version
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up Flutter
        script: |
          flutter precache --ios
          flutter --version
          flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa