workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "3.29.2"
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Install CocoaPods
        script: |
          echo "CocoaPods will be automatically installed by Codemagic"
      - flutter --version
      - flutter pub get
      - cd ios && pod install --repo-update && cd ..
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa