workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "3.29.2"
      groups:
        - ios
    scripts:
      - name: Force Flutter Engine Download
        script: |
          # Clean and redownload Flutter engine
          rm -rf $FLUTTER_ROOT/bin/cache/artifacts/engine/ios
          flutter precache --ios --force
          
          # Verify engine files exist
          ls -la $FLUTTER_ROOT/bin/cache/artifacts/engine/ios/
          [ ! -f "$FLUTTER_ROOT/bin/cache/artifacts/engine/ios/Flutter.podspec" ] && exit 1

      - name: Install Pods with Absolute Path
        script: |
          cd ios
          cat > Podfile << 'EOL'
          platform :ios, '13.0'
          use_frameworks!

          target 'Runner' do
            pod 'Flutter', :path => ENV['FLUTTER_ROOT'] + '/bin/cache/artifacts/engine/ios'
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
              end
            end
          end
          EOL
          
          pod install --verbose --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa