workflows:
  ios-workflow:
    name: iOS Build
    environment:
      # Set Flutter version FIRST (top-level key)
      flutter: "3.29.2"  # Matches Dart 3.7.2+
      groups:
        - ios
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Verify Versions
        script: |
          flutter --version  # Should show 3.29.2
          dart --version    # Should show 3.7.2+
      - flutter pub get
      - cd ios && pod install --repo-update && cd ..
      - flutter build ios --release --no-codesign