workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: "3.29.2"
      xcode: latest
      cocoapods: default
      groups:
        - ios
    scripts:
      - name: Pre-cache Flutter & iOS artifacts
        script: |
          flutter doctor
          flutter pub get
          flutter precache --ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
