# ios/Podfile
platform :ios, '13.0'  # Required for cloud_firestore
use_frameworks!  # Needed for some Firebase plugins

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end